### ISSUE TITLE
Assign a version tag to repos under lwa-shell and update config

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#98] opened 2022-04-01 20:33 UTC
A number of the repos under lwa-shell do not have a version tag. If the API is still in flux, v0.x.x is recommended. When the repos' get tagged, then the .mrconfig_production file in lwa-shell can be updated to identify the tag to checkout. The version of lwa-shell should also be bumped to allow rollback and such.

**Comment by caseyjlaw** [comment] 2023-03-29 19:44
Duplicate of #296. We'll manage it over there.

**Closed by caseyjlaw** 2023-03-29 19:44 UTC
Labels: production
