### ISSUE TITLE
Xengine Control + Data Recording Issues

### ISSUE THREAD

**Issue by iveydavis** [ovro-lwa/lwa-issues#162] opened 2022-10-14 22:54 UTC
I ran into a few issues/peculiarities while running observing tests following the system use recipe.

note, `con` is defined from:
```
from mnc import control
con = control.Controller('config/lwa_config_calim.yaml')
```
First, it's not clear that `con.stop_xengine()` actually stopped the x-engine. This is the output from checking the status after running it:
![Capture](https://user-images.githubusercontent.com/29830471/195953844-395926e9-2706-4c3f-8d8f-f64e8da8e568.PNG)

Which appears to be the same as the output when running `con.start_xengine()`  (first screenshot is the immediate output of running this, the second screenshot is the result of checking the status):

![Capture2](https://user-images.githubusercontent.com/29830471/195954066-bfa325f9-e5b6-4d0b-8e17-3b37c7ece9b6.PNG)
![Capture3](https://user-images.githubusercontent.com/29830471/195953902-a3a433bf-1e9f-47f2-a2e8-fe98162444c3.PNG)

I tried running `con.start_dr(recorders=['drvs'])` and got the following message:
![Capture5](https://user-images.githubusercontent.com/29830471/195954403-b0ae65ca-bfe3-45bd-9379-cbf6f3723c9d.PNG)

It didn't record anything and it's not clear to me why I would get a message about the beamformer when I'm just trying to record a slow visibility.  I tried to 'circumvent' the problem by getting the beamformer ready to record too, but got the following error:
![Capture9](https://user-images.githubusercontent.com/29830471/195954826-f7368505-9d22-4bc7-9291-b0b0ca496cf6.PNG)

Assigning a target to track returns the same error:
![Capture10](https://user-images.githubusercontent.com/29830471/195954569-fe530320-2294-4320-aa26-db3d3a81b1bc.PNG)

After all the failures, I tried running `con.stop_xengine()` again, but it's still unclear to me that it actually stopped the xengine. I'll need to look at the logs more closely.

**Comment by jaycedowell** [comment] 2022-10-18 21:32
I just ran into something similar to your `con.start_xengine_bf()` error but through a direct interaction with the `mnc.xengine_beamformer_control` module.  For me the root cause of the `KeyError: 'chan0'` came from not all of the xengine pipelines receiving data.  No data flowing into the pipeline, no way to know what `chan0` is.  This happened because I naively used the old `lwa_corr_config_haarp.yaml` configuration for the SNAPs which was pre-the IP addresses getting changed on lxdlwagpu##.  Wrong IP address, no data into the pipelines.

**Comment by iveydavis** [comment] 2022-10-18 21:45
Are you running this on gpu09 or calim00? I'd hoped to use `mnc.xengine_beamformer_control` to investigate the problem, but I can't check the status of the data recording services on calim00.

**Comment by jaycedowell** [comment] 2022-10-18 21:48
I'm on calim00 right now.  Yeah, you cannot directly check on the data recorders  a la `like_bmon.py` from 00.  The monitoring points should work through a `mnc.mcs.Client` instance though.

**Comment by jaycedowell** [comment] 2022-10-21 19:31
@caseyjlaw and I did some work on this. I would like to think that this is resolved.

**Comment by caseyjlaw** [comment] 2022-10-21 19:37
Yes, this should be resolved by the fix to the configuration file change (on cjl/dev). I'll merge that in to main.

**Closed by caseyjlaw** 2022-10-21 19:37 UTC
Labels: bug, M/C

**Comment by caseyjlaw** [comment] 2022-11-03 15:42
@jaycedowell I think we ran into this issue again after reprogramming snaps. The `mnc-python` config file didn't change, but it now reports this error when running beamformers and a sync error when configuring for slow visibilities.
I'll test again, but can you recommend a centralized way to check whether the config is mapping f- to x-engine correctly?

**Comment by caseyjlaw** [comment] 2022-11-03 17:56
I fixed a configuration error and rerun an observing test with slow vis and power beams 1 and 2. No issues.
The error must have been copied in when resolving this issue (snap02 was not included and a non-existent "snap12" was added).

**Comment by caseyjlaw** [comment] 2022-12-14 17:38
I saw this error again and noticed in the dashboard that one of the pipelines on gpu3 was down. Stopping and reconfiguring the xengines cleared the issue.
