### ISSUE TITLE
Beamformer recording output not found

### ISSUE THREAD

**Issue by dgary50** [ovro-lwa/lwa-issues#105] opened 2022-04-14 18:33 UTC
In following the system use recipe for beam form observing, everything seemed to go correctly but on starting the data recording we could not find a new datafile in the standard location ~/data/beam01/.  The log file showed the filename and indicated that it was recording, but does not include the path so it is possible the file was being written elsewhere.  We stopped and restarted the service and tried a second time with no change to the result.

**Comment by rh-codebase** [comment] 2022-04-14 18:56
On lxdlwagpu09 I see:
(casa) ubuntu@lxdlwagpu09:~$ ls -lrt ~/data/
total 76
drwxr-xr-x 2 ubuntu ubuntu 61440 Apr  5 17:16 slow
drwxr-xr-x 2 ubuntu ubuntu  4096 Apr 13 15:12 beam02
drwxr-xr-x 2 ubuntu ubuntu  4096 Apr 13 15:12 beam01
drwxr-xr-x 2 ubuntu ubuntu  4096 Apr 14 08:45 beam03
drwxr-xr-x 2 ubuntu ubuntu  4096 Apr 14 09:05 beam04

maybe the file is under beam03 or beam04?  What's the filename?

**Comment by jaycedowell** [comment] 2022-04-14 19:09
Looking at the dr-beam-1 log around the time of the recording I see:
```
...
2022-04-14 18:16:12 [INFO    ] HDF5Record - Scheduled recording for 2022-04-14 18:16:27.366142 to 2022-04-14 18:46:27.366142 to /home/ubuntu/data/beam01/059683_181627366142f72d537
2022-04-14 18:16:14 [DEBUG   ] === Performance Report ===
2022-04-14 18:16:14 [DEBUG   ]  max acquire/process/reserve times: 0.000/0.000/0.000
2022-04-14 18:16:14 [DEBUG   ]  pipeline lag: 0.0
2022-04-14 18:16:14 [DEBUG   ]  load average: 1.00, 1.16, 0.84
2022-04-14 18:16:14 [DEBUG   ] ===   ===
...
```

What's interesting about this is the max  *times and pipeline lag values are all zero.  That suggests that the digital system wasn't sending any data to the recorder.

**Comment by rh-codebase** [comment] 2022-04-14 19:26
what host is this on?

**Comment by jaycedowell** [comment] 2022-04-14 19:27
lxdlwagpu09

**Comment by rh-codebase** [comment] 2022-04-14 19:28
ok. so zero length files are not created then? I don't see this filename where the log message states.

**Comment by jaycedowell** [comment] 2022-04-14 19:30
That's right.  If the recorder isn't receiving data then no file is created, not even a zero length one.

**Comment by dgary50** [comment] 2022-04-15 13:17
What indication would we have if the digital system is not sending data?  All the pipelines indicated good operation.  There were some warnings about no PPS when configuring the SNAPs, but I think those are "normal."

**Comment by jaycedowell** [comment] 2022-04-15 13:24
One option would be to run the `like_bmon.py` utility on lxdlwagpu09.  This utility shows the packet capture statistics of all running recorder pipelines on that machine.

**Comment by caseyjlaw** [comment] 2022-04-15 13:32
@rh-codebase Do we have any of the monitor points related to data capture being ingested to influx? It would be nice to have a dashboard to display this info.

**Comment by jaycedowell** [comment] 2022-04-15 13:44
This might be a case where higher-level monitoring points would be useful.  You could imagine situations where:
 * The digital pipelines are running but not receive any data from the snaps so nothing is coming out.
 * The digital pipelines are running and receiving/processing data but not configured to output a beam so nothing is coming out.
Both of these might be ok from "are the digital pipelines running" perspective but lead to a situation where you aren't getting what you expect.  Interestingly enough the recorder's `summary` monitor point does not go to "error" when no data are being received.  I didn't  consider no data to be an error condition.

**Comment by rh-codebase** [comment] 2022-04-15 16:24
Not yet. How quickly this happens will depend on how flat the monitor data are. What etcd key is it going under? The ingest is designed to map an etcd key to an influxdb table but the dictionary under the etcd key needs to be flat as in key:value only. Otherwise a special parser needs to be coded. I'll take a look at the monitor data and go from there.

**Comment by jack-h** [comment] 2022-04-19 17:13
@rh-codebase When did GPU09's IP address change? Could this be relevant?

**Comment by jaycedowell** [comment] 2022-04-19 17:27
Even if it wasn't relevant then it is now and I need to update the systemd service files.

**Comment by jack-h** [comment] 2022-04-19 17:30
Per a recent email from @rh-codebase (Sat 16th April 2022), IP addresses now in use are:
```
| host        | IP 10.41.0.xx/26  |   |
|-------------+-------------------+---|
| lxdlwagpu01 |                65 |   |
| lxdlwagpu02 |                66 |   |
| lxdlwagpu03 |                67 |   |
| lxdlwagpu04 |                68 |   |
| lxdlwagpu05 |                69 |   |
| lxdlwagpu06 |                70 |   |
| lxdlwagpu07 |                71 |   |
| lxdlwagpu08 |                72 |   |
| lxdlwagpu09 |                73 |   |
| lwacalim00  |                74 |   |
```

**Comment by jaycedowell** [comment] 2022-04-19 17:33
10.41.0.xx/28 is the same as it was?

**Comment by jack-h** [comment] 2022-04-19 17:35
I believe so

**Comment by rh-codebase** [comment] 2022-04-19 18:08
only 1 of the /28 in 10.41.0.0/24 was moved to a /26. Here's the complete table:

`| host        | IP 10.41.0.xxx/26 | 10.41.0.xx/28 |
|-------------+-------------------+---------------|
| lxdlwagpu01 |                65 |            18 |
| lxdlwagpu02 |                66 |            17 |
| lxdlwagpu03 |                67 |            19 |
| lxdlwagpu04 |                68 |            20 |
| lxdlwagpu05 |                69 |            21 |
| lxdlwagpu06 |                70 |            22 |
| lxdlwagpu07 |                71 |            23 |
| lxdlwagpu08 |                72 |            24 |
| lxdlwagpu09 |                73 |            25 |
| lwacalim00  |                74 |            -  |`

**Comment by jaycedowell** [comment] 2022-04-19 19:20
I've updated the `p.configure_corr()` portion of the system use recipe and the data recorder service files.

**Comment by jack-h** [comment] 2022-04-21 12:04
It's still not 100% clear to me if this issue was caused by the IP changes
(which I thought happened after the beamforming failure), but beamformer
recording was tested on Weds 20th April and worked fine.

**Comment by marinanderson** [comment] 2022-04-27 18:44
I think I was seeing this issue again when attempting to collect slow visibilities this morning.

From one of the dr-vslow logs:
```
2022-04-27 18:29:15 [DEBUG   ] === Performance Report ===
2022-04-27 18:29:15 [DEBUG   ]  max acquire/process/reserve times: 0.000/0.000/0.000
2022-04-27 18:29:15 [DEBUG   ]  pipeline lag: 0.0
2022-04-27 18:29:15 [DEBUG   ]  load average: 3.25, 3.60, 3.37
```

Looks like digital system was not sending anything to the data recorder?

I was unable to bring the gpu01 pipelines up (my usual tricks of restarting the lwa-xeng-etcd.service and running sudo /etc/init.d/openibd restart didn't work). The rest appeared to come up fine, but when running `p.configure_corr` I got
```
2022-04-27 18:43:45 [WARNING ] It looks like the pipeline is -433412 seconds ahead of the expected spectra number
2022-04-27 18:43:46 [WARNING ] Pipeline lxdlwagpu01:0 not in expected waiting state after arm
2022-04-27 18:43:46 [WARNING ] Pipeline lxdlwagpu01:1 not in expected waiting state after arm
2022-04-27 18:43:47 [WARNING ] Pipeline lxdlwagpu01:2 not in expected waiting state after arm
2022-04-27 18:43:47 [WARNING ] Pipeline lxdlwagpu01:3 not in expected waiting state after arm
2022-04-27 18:43:47 [INFO    ] Waiting 10 seconds for trigger
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu02:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu02:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu02:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu02:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu03:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu03:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu03:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu03:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu04:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu04:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu04:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu04:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu05:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu05:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu05:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu05:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu06:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu06:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu06:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu06:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu07:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu07:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu07:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu07:3 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu08:0 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu08:1 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu08:2 not in expected running state
2022-04-27 18:43:57 [WARNING ] Pipeline lxdlwagpu08:3 not in expected running state
```

**Comment by rh-codebase** [comment] 2022-04-27 19:08
That's a really big time offset -- behind by ~ 5 days.

**Comment by marinanderson** [comment] 2022-04-27 19:41
Yeah...I tried re-initializing the SNAPs to correct that, but didn't work.

**Comment by jack-h** [comment] 2022-04-28 18:34
This is definitely a different issue than the original beamformer problem (which was traced to a configuration error)
I had issues just now, which I attribute to the earlier death of the etcd server (issue #110 ). I Restarted the X-engines etcd clients -- `systemctl restart bifrost_etcd_bridge.service` and then everything started fine.
But I think this is different to your issue, which is probably related to the warning about a time stamp being different from expected -- the control command will have told the system to start sending data 10 seconds in the future, but the system is running with its internal time 5 days slow! If you'd waited for a week, probably data would have started flowing!

**Comment by jack-h** [comment] 2022-04-28 18:37
In any case, I'm going to close this issue since I think the original (beamforming) problem was identified.

**Comment by jack-h** [comment] 2022-04-28 18:38
Ha, I don't think I have permissions to close :)

**Comment by jack-h** [comment] 2022-04-28 18:40
Wait... now I get it. What will have happened is that the etcd crash will have meant the timestamps in etcd were all stale. Probably the system was up to date with current time, but the time stored in etcd (used by the arming routine) was old. Hence, no arm. Hence, no data.

**Closed** 2022-04-28 18:40 UTC
